# Generated by Django 3.1 on 2021-05-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTableForPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.format')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.ManyToManyField(through='books.ExtraTableForPrice', to='books.Format'),
        ),
    ]
