# Generated by Django 3.1 on 2021-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210512_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratableforprice',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_price', to='books.book'),
        ),
        migrations.AlterField(
            model_name='extratableforprice',
            name='formats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_price', to='books.format'),
        ),
    ]
