# Generated by Django 3.1 on 2021-05-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210511_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extratableforprice',
            old_name='book',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='extratableforprice',
            old_name='format',
            new_name='formats',
        ),
    ]
